### ISSUE TITLE
The ‘Google link’ is empty?

### ISSUE THREAD

**Issue by CreaterLL** [truthless11/CR-Walker#1]
Hello, the 'google link' link is empty, is it not uploaded data yet?

**Comment by CreaterLL** [comment]
I'm not sure if it's a problem with my device.

**Comment by Arthurma71** [comment]
Yes we'll upload it as soon as possible. Sry fo the inconvience

**Comment by truthless11** [comment]
@CreaterLL The files including data and model checkpoints have been uploaded.

**Comment by CreaterLL** [comment]
i got it ,thank you!
