### ISSUE TITLE
Confused by some errors

### ISSUE THREAD

**Issue by CreaterLL** [truthless11/CR-Walker#2]
Excuse me,  i haven't found the gorecdial_gpt and redial_gpt, and when I ran python train_gorecdial.py -- option train -- model_name <your_model_name>  --Pretrain, I'm a little confused by the following error: No such file or directory:'./CR-Walker-main/data/id2name_gorecdial.json',where is the "id2name_gorecdial" come from?Is it because my code is executed in the wrong order?

**Comment by Arthurma71** [comment]
Both id2name files has been uploaded, along with data needed for the MIM pretraining.  Generation models on both dataset will be uploaded within this week, so stay posted!
