### ISSUE TITLE
Could not infer dtype of NoneType

### ISSUE THREAD

**Issue by bbwen** [truthless11/CR-Walker#3]
Hi, I'm wondering if the code is ready to run. I met the problem when I run either train or test command. Could you help me with this issue?

**Comment by truthless11** [comment]
Please show us the details on what problem you have encountered (e.g. a screenshot)

**Comment by bbwen** [comment]
Here is the screenshot. 
![image](https://user-images.githubusercontent.com/63829821/146154967-b7908b3f-6905-405b-ac09-e7b69deff886.png)

**Comment by Arthurma71** [comment]
Please check your version for torch-geometric==1.6.0. The latest version for torch_geometric has a slightly different version of in_memory_dataset.

**Comment by Arthurma71** [comment]
![76b215dcd523dd2a2013cb42f133a85](https://user-images.githubusercontent.com/34963577/146155882-c90aac26-78ef-444b-920d-38b5ff380186.png) This is the collate function in the correct version of torch-geometric
